name: CI

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: "22"
      package-manager:
        type: string
        default: "pnpm"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
        if: inputs.package-manager == 'pnpm'
        with:
          version: latest

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.package-manager }}

      - name: Install
        run: ${{ inputs.package-manager }} install --frozen-lockfile

      - name: Typecheck
        run: ${{ inputs.package-manager }} typecheck

      - name: Lint
        run: ${{ inputs.package-manager }} lint

      - name: Test
        run: ${{ inputs.package-manager }} test

      - name: Build
        run: ${{ inputs.package-manager }} build
